### PR TITLE
Fix for #254 - booleans that are written as strings cannot be parsed

### PR DESCRIPTION
**Pull request by ptgeorge**

### CODE REVIEW

**Comment by apparentlymart** [comment]
Thanks for working on this, @ptgeorge!

Looking at the surrounding functions, I see that there was indeed precedent for this sort of conversion for the numeric types, but was missed for booleans.

With that said, [we have a next-generation HCL implementation landing here soon](https://github.com/hashicorp/hcl/wiki/HCL-2.0-Transition), and _its_ interpretation of strings as bools has a more limited set of valid inputs in an effort to encourage consistency of usage: `true`, `false`, `0`, `1`. To avoid introducing a whole load of new possibilities in HCL 1 right before we switch to HCL 2 which doesn't support them, I'd prefer to limit the conversions here also to that set.

Would you be willing to revise this to use a `switch` statement over the four strings above, rather than using Go's `ParseBool` here? It'd be nice also to add a test case to `decoder_test.go` that covers these; it looks like the existing `TestDecode_intString` is doing a similar sort of thing.

If you don't have further time to spend on this please let me know; I'm happy to add these revisions to my own list and address them when I next have a spare moment.

Thanks again for finding and fixing this bug!

**Comment by ptgeorge** [comment]
Yes I can adjust it to work in that fashion, while still stripping the double quotes and then adding the conversion to lower case.

It was unclear to me how stable or how far away HCL2 was when I looked at it last week.  When is a stable release of HCL2 expected?

**Comment by ptgeorge** [comment]
Adjustments made as requested.

**Comment by apparentlymart** [comment]
Looks good. Thanks!

HCL 2's schedule is driven by Terraform's, since Terraform is the first user of it. It will be tagged as a release at some point late in the pre-release phase of Terraform 0.12 (likely in time for its first release candidate), but there is no yet any specific date associated with that because development has not yet reached feature complete.

Until we tag it as 2.0.0 and put it in this repository the HCL 2 API is subject to change, but in practice _major_ changes are unlikely since the API is now used deeply within Terraform.

**Pull request merged**
