### PR TITLE
Support float32 decoding

### PR DESCRIPTION
**Pull request by JelteF**
Right now it fails with the message: 
```
unknown kind to decode into: float32
```

### CODE REVIEW

**Comment by apparentlymart** [comment]
Hi @JelteF! Thanks so much for this.

If you have time, it'd be great to also have a test for this in `decoder_test.go`, to help us ensure that this behavior doesn't get broken by future work. If you don't have time, please let me know.

**Comment by JelteF** [comment]
Hi @apparentlymart I don't really have time for that at the moment.

**Comment by apparentlymart** [comment]
Okay, no worries! I will take a look at that myself when I have some time.

**Comment by apparentlymart** [comment]
Hi again @JelteF!

I just merged your change. I added a test and then found that what you had done wasn't quite enough since it was panicking trying to assign a `float64` value into a `float32`, so I added an extra conversion to make it behave as expected.

Thanks for this!

**Pull request merged**
