### PR TITLE
Added hcl to json example for nested objects

### PR DESCRIPTION
**Pull request by timgent**
It was unclear how nested object example in hcl would map to json. Readme now updated to include an example of the json equivalent to a hcl nested object

### CODE REVIEW

**Comment by jonashaag** [comment]
:+1:

**Comment by sheerun** [comment]
Could you add example when multiple variables are defined?

**Comment by sheerun** [comment]
e.g. 

```
resource "foo" "bar" {

}

resource "foo" "fiz" {

}
```

**Comment by timgent** [comment]
I've rebased this to master so ready to merge but not sure how the hcl you've provided would map to json. Do you have the equivalent in json?

**Comment by sheerun** [comment]
I have no idea

**Comment by jen20** [comment]
Thanks for this @timgent! It certainly makes the usage of JSON a bit more obvious. I don't know what's up with Appveyor here, presumably the base was already broken. I'm not too worried though since the diff clearly only affects the README.

**Pull request merged**
