### PR TITLE
parser: fix syntax error on missing comma

### PR DESCRIPTION
**Pull request by fatih**
Fixes hashicorp/terraform#3877

### CODE REVIEW

**Comment by sethvargo** [comment]
@fatih so this fixes the issue :smile: but do we want to fix it?

**Comment by sethvargo** [comment]
I kinda like not having to specify commas... /cc @mitchellh

**Comment by fatih** [comment]
@sethvargo just added a test case for it. I think the new parser should be backwards compatible. This also fixes like cases for `["123" "456"]` which were not reported as errors. For multiline lists we might decide to neglect it, but as said I'm usually in favor of respecting backwards compatibility :)

**Comment by sethvargo** [comment]
@fatih is it breaking backwards compat? Having commas still works and not having them also works :smile:

**Comment by fatih** [comment]
@sethvargo oh :) If I didn't miss read here https://github.com/hashicorp/terraform/issues/3877 you're saying that it *errors* on` 0.6.6`, which I've assumed that `0.6.6` uses the old parser

**Comment by sethvargo** [comment]
@fatih haha no problem. Let me clarify:

- The current version of Terraform 0.6.6, which uses the old parser, requires commas to separate values in arrays.
- The master branch of Terraform (0.6.7.dev), which uses the new parser, does not require commas to separate values in arrays.

```javascript
// Works in 0.6.6
inline = [
  "foo",
  "bar",
]

// Works in 0.6.7
inline = [
  "foo",
  "bar",
]
```

```javascript
// Does not work in 0.6.6
inline = [
  "foo"
  "bar"
]

// Works in 0.6.7
inline = [
  "foo"
  "bar"
]
```

Does that help clarify?

**Comment by fatih** [comment]
Alright this now makes sense :+1:  So when I mean we should respect backwards compatibility, I was saying we should return an error for this case:

```
// Does not work in 0.6.6
inline = [
  "foo"
  "bar"
]
```

Right now, without this fix, the following also works (which imho should return also an error):

```
inline = ["foo" "bar"]
```

The parser doesn't check the newlines in any case. Having the comma is better for us, because it would make the parser more simpler and in the long term more stable. If we allow multiline lists without commas, we need to have fix it by also respecting newlines. This again, in my opinion, would complicate the parser.

I'm open to changes though :) I'm kinda following the philosophy of Go, basically having strict rules, explicitly over implicitly, and so on.

**Comment by sethvargo** [comment]
Fair enough. I can deal :smile:

**Comment by mitchellh** [comment]
I don't want to introduce new syntax into HCL and I prefer having commas. My preference is that we support trailing commas (which we do), but not the no comma case. This looks good to me. Thanks!

**Pull request merged**
