### PR TITLE
missing fields when decoding JSON

### PR DESCRIPTION
**Pull request by jbardin**
A single JSON object with a single key and value of a another object fails to decode.

### CODE REVIEW

**Comment by jbardin** [comment]
This will fix #153

**Comment by jbardin** [comment]
back to WIP -- this doesn't solve the terraform issue, so we need to expand maps in some cases too.

**Comment by jbardin** [comment]
All tests green! 🍏

**Comment by mitchellh** [comment]
Looks really great! :D

**Comment by jbardin** [comment]
rebased in some spelling/comment fixes.

**Pull request merged**
