### PR TITLE
Return PosError instead of error in more cases

### PR DESCRIPTION
**Pull request by mauve**
ran `go test` locally to test

### CODE REVIEW

**Comment by mauve** [comment]
ping?

**Comment by mauve** [comment]
hello?

**Comment by apparentlymart** [comment]
Hi @mauve! Sorry for the delay here.

This seems good to me. Thanks for working on it!

**Comment by mauve** [comment]
@apparentlymart thanks for merging, this was _needed_ for my project https://github.com/mauve/terraform-index (which is a small helper for a vscode plugin I wrote)

**Pull request merged**
